-- CREATE EMPLOYEES TABLE
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT UNIQUE,
    POSITION VARCHAR(50) NOT NULL,
    HIRE_DATE DATE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- CREATE USERS TABLE
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    BALANCE DECIMAL(10, 2) DEFAULT 0.0
    TOKEN VARCHAR(255)
);


-- CREATE CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT UNIQUE,
    ACCOUNT_NUMBER VARCHAR(20) UNIQUE NOT NULL,
    ACCOUNT_TYPE VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- CREATE PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10, 2) NOT NULL
);

-- INSERT AN EMPLOYEE WITH THE POSITION OF MANAGER
INSERT INTO EMPLOYEES (USER_ID, POSITION, HIRE_DATE)
VALUES
    (USER_ID_VALUE, 'MANAGER', '1996-02-04');


-- CREATE LOG TABLE
CREATE TABLE LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    ACTIVITY_TYPE VARCHAR(50) NOT NULL,
    ACTIVITY_DESCRIPTION TEXT,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);







